@shop_HostAddress = http://localhost:15001

### Status
GET {{shop_HostAddress}}/status/
Accept: application/json

### Reset
GET {{shop_HostAddress}}/reset/
Accept: application/json

### Login
GET {{shop_HostAddress}}/login?username="sokoide@ms.com"
Accept: application/json
###
GET {{shop_HostAddress}}/break/0/
Accept: application/json
###
GET {{shop_HostAddress}}/fix/0/
Accept: application/json
###
GET {{shop_HostAddress}}/status/0/
Accept: application/json

### Products
GET {{shop_HostAddress}}/products/
Accept: application/json
###
GET {{shop_HostAddress}}/break/1/
Accept: application/json
###
GET {{shop_HostAddress}}/fix/1/
Accept: application/json
###
GET {{shop_HostAddress}}/status/1/
Accept: application/json

### Chekcout
POST {{shop_HostAddress}}/2/
Content-Type: application/json
Accept: application/json

{
    "1": 0,
    "2": 3,
    "3": 4
}
###
GET {{shop_HostAddress}}/break/2/
Accept: application/json
###
GET {{shop_HostAddress}}/fix/2/
Accept: application/json
###
GET {{shop_HostAddress}}/status/2/
Accept: application/json

### Delivery
GET {{shop_HostAddress}}/3/
Accept: application/json
###
GET {{shop_HostAddress}}/break/3/
Accept: application/json
###
GET {{shop_HostAddress}}/fix/3/
Accept: application/json
###
GET {{shop_HostAddress}}/status/3/
Accept: application/json
